package main

// Kept separate so the premium surface language remains easy to art-direct.
// Every visible string exists in all supported languages.
var premiumTextByLanguage = map[string]map[string]string{
	"it": {
		"textureEyebrow": "PERFETTA • TEXTURE ULTRA PREMIUM", "textureTitle": "Scegli la firma della superficie", "textureSubtitle": "Finiture generate dai percorsi reali dello slicer, calibrate per qualità, dettaglio e resistenza.",
		"textureSatin": "Satin Pro", "textureSatinDesc": "Seta uniforme con ironing controllato. Ideale per superfici lisce e precise.",
		"texturePrism": "Crystal Prism", "texturePrismDesc": "Percorso ottagramma luminoso, deciso e geometrico. Nessuna perdita di pareti.",
		"textureCarbon": "Carbon Weave", "textureCarbonDesc": "Intreccio Hilbert e microtexture sul solo contorno esterno.",
		"textureTopo": "Topographic Flow", "textureTopoDesc": "Curve concentriche organiche come una mappa topografica.",
		"textureApplied": "Profilo Perfetta • 4 pareti • Arachne • guscio superiore 1,0 mm", "textureApply": "Applica texture", "textureSelected": "SELEZIONATA",
	},
	"en": {
		"textureEyebrow": "PERFECT • ULTRA PREMIUM TEXTURES", "textureTitle": "Choose your surface signature", "textureSubtitle": "Finishes generated by real slicer paths, calibrated for quality, detail and strength.",
		"textureSatin": "Satin Pro", "textureSatinDesc": "Even silk with controlled ironing. Ideal for smooth, precise surfaces.",
		"texturePrism": "Crystal Prism", "texturePrismDesc": "A bright, geometric octagram path. No wall strength sacrificed.",
		"textureCarbon": "Carbon Weave", "textureCarbonDesc": "Hilbert weave with microtexture on the outer contour only.",
		"textureTopo": "Topographic Flow", "textureTopoDesc": "Organic concentric curves inspired by topographic maps.",
		"textureApplied": "Perfect profile • 4 walls • Arachne • 1.0 mm top shell", "textureApply": "Apply texture", "textureSelected": "SELECTED",
	},
	"fr": {
		"textureEyebrow": "PARFAITE • TEXTURES ULTRA PREMIUM", "textureTitle": "Choisissez la signature de surface", "textureSubtitle": "Finitions créées par les trajectoires réelles du slicer, calibrées pour qualité, détail et résistance.",
		"textureSatin": "Satin Pro", "textureSatinDesc": "Soie uniforme avec lissage contrôlé, pour des surfaces lisses et précises.",
		"texturePrism": "Crystal Prism", "texturePrismDesc": "Trajectoire octagramme lumineuse et géométrique, sans sacrifier les parois.",
		"textureCarbon": "Carbon Weave", "textureCarbonDesc": "Trame Hilbert et microtexture uniquement sur le contour extérieur.",
		"textureTopo": "Topographic Flow", "textureTopoDesc": "Courbes concentriques organiques inspirées des cartes topographiques.",
		"textureApplied": "Profil Parfaite • 4 parois • Arachne • coque supérieure 1,0 mm", "textureApply": "Appliquer la texture", "textureSelected": "SÉLECTIONNÉE",
	},
	"es": {
		"textureEyebrow": "PERFECTA • TEXTURAS ULTRA PREMIUM", "textureTitle": "Elige la firma de la superficie", "textureSubtitle": "Acabados creados por trayectorias reales del laminador, calibrados para calidad, detalle y resistencia.",
		"textureSatin": "Satin Pro", "textureSatinDesc": "Seda uniforme con alisado controlado, ideal para superficies lisas y precisas.",
		"texturePrism": "Crystal Prism", "texturePrismDesc": "Trayectoria octagrama luminosa y geométrica, sin sacrificar paredes.",
		"textureCarbon": "Carbon Weave", "textureCarbonDesc": "Trama Hilbert y microtextura solo en el contorno exterior.",
		"textureTopo": "Topographic Flow", "textureTopoDesc": "Curvas concéntricas orgánicas inspiradas en mapas topográficos.",
		"textureApplied": "Perfil Perfecta • 4 paredes • Arachne • capa superior de 1,0 mm", "textureApply": "Aplicar textura", "textureSelected": "SELECCIONADA",
	},
	"de": {
		"textureEyebrow": "PERFEKT • ULTRA-PREMIUM-TEXTUREN", "textureTitle": "Wähle die Signatur der Oberfläche", "textureSubtitle": "Oberflächen aus echten Slicer-Pfaden, abgestimmt auf Qualität, Detail und Festigkeit.",
		"textureSatin": "Satin Pro", "textureSatinDesc": "Gleichmäßige Seide mit kontrolliertem Glätten für präzise Oberflächen.",
		"texturePrism": "Crystal Prism", "texturePrismDesc": "Leuchtender geometrischer Oktagramm-Pfad ohne schwächere Wände.",
		"textureCarbon": "Carbon Weave", "textureCarbonDesc": "Hilbert-Gewebe und Mikrotextur nur an der Außenkontur.",
		"textureTopo": "Topographic Flow", "textureTopoDesc": "Organische konzentrische Kurven wie auf topografischen Karten.",
		"textureApplied": "Profil Perfekt • 4 Wände • Arachne • 1,0 mm Deckschale", "textureApply": "Textur anwenden", "textureSelected": "AUSGEWÄHLT",
	},
}
